#include "mapi_errors.h"

const errorstruct Errors[] = {
{1025 , "libpcap:Error in BPF filter"},
{1026 , "libpcap: Error opening pcap link"},
{1027 , "libpcap: Error creating pcap_t structure"},
{1100 , "mapinicdrv: Error in pthread"},
{1200 , "Combo6drv: Error opening device"},
{1201 , "Combo6drv: Error in pthread"},
{1202 , "Combo6: could not read option"},
{1203 , "Combo6: could not read STU"},
{1300 , "Dagdrv: Error opening device"},
{1301 , "Dagdrv: Error in pthread"},
{1302 , "Dagdrv: Error accessing mmap buffer"},
{1303 , "Dagdrv: Error starting driver"},
{1400 , "mapivindrv: Error in pthread"},
{1401 , "mapivindrv: Does not support offline flows"},
{1402 , "mapivindrv: devid not foun in devlist"},
{1501 , "mapidrv: Does not support offline flows"},
{1600 , "NapatechDrv: Error in pthread"},
{1601 , "NapatechDrv: Failed to find a card to use"},
{1602 , "NapatechDrv: Failed to shut down other packet feeds"},
{3073 , "Error not found"},
{3074 , "Invalid flow descriptor"},
{3075 , "Error allocating shared memory"},
{3076 , "Error allocating semaphore"},
{3077 , "Error creating temporary file"},
{3078 , "Invalid function ID"},
{3079 , "Function not found"},
{3080 , "Could not apply function"},
{3081 , "Flow already active"},
{3082 , "No support for functions that modify packets"},
{3083 , "File already exists"},
{3139 , "Flow is not authenticated"},
{3200 , "No driver found for this device"},
{3201 , "Could not receive file descriptor"},
{3202 , "No such device"},
{3500 , "Error Loading lib_ethereal shared library"},
{3501 , "Error lib_ethereal, function symbol not found"},
{3502 , "Error in ethereal filter"},
{3503 , "Unterminated '|' in pattern declaration"},
{3504 , "The specified depth is less than the size of the pattern"},
{3505 , "Invalid search string."},
{5121 , "Unknown error in IPC communication"},
{5122 , "Error on acknowledgement in IPC communication"},
{5123 , "Error reading from or writing to socket"},
{5124 , "Error creating client socket"},
{6140 , "Error MAPI shutdown in progress"},
{6141 , "Error MAPI not Initialized"},
{6142 , "Error on mapi connect"},
{6143 , "Error while trying to read from a not connected flow"},
{6144 , "Function not found"},
{6145 , "Invalid mapi flow descriptor"},
{6146 , "Error attaching shared memory. Probably you are trying to read results from a function that does not return any results."},
{6147 , "Invalid flow or function descriptor"},
{6148 , "Error acessing semaphore"},
{6149 , "Error accessing flow information"},
{6150 , "Error accessing function information"},
{6151 , "Error loading library"},
{6152 , "Error getting libpath from mapid"},
{6153 , "Error getting libraries from mapid"},
{6154 , "Error getting current path"},
{6155 , "Error opening file"},
{6156 , "Error sending file descriptor"},
{6149 , "Error accessing device information"},
{7000 , "Invalid argument passed to function"},
{7001 , "First argument passed to function is invalid"},
{7002 , "Second argument passed to function is invalid"},
{7003 , "Third argument passed to function is invalid"},
{7004 , "Fourth argument passed to function is invalid"},
{7005 , "Fifth argument passed to function is invalid"},
{7006 , "Could not apply function"},
{7007 , "Could not initialize function"},
{7008 , "Semaphore error"},
{7009 , "Not supported"},
{7010 , "Invalid argument descriptor"},
{7011 , "Sixth argument passed to function is invalid"},
{8000 , "Admission control memory allocation error"},
{8001 , "No authentication/authorization data set"},
{8002 , "Communication error with admission control"},
{8003 , "Authorization failed"},
{8004 , "Error in mapi_stats"},
{3084 , "Error Allocating Memory"},
{0,0}
};
