#!/bin/bash
function test {
    if [ $1 = 0 ] ; then
	echo OK
    else
	echo Failed
	exit;
    fi
}

tests=(
test_map2
test_map3
test_map4
test_map5
test_map6
);

for test_file in ${tests[@]}; do 
	echo -n $test_file":"
	if [ "$1" == "-v" ]; then
		./$test_file ../www.trace testing_$test_file.trace 
	else
		./$test_file ../www.trace testing_$test_file.trace > /dev/null
	fi
	test $?
	i=$i+1
done
