.\" MAPI man page
.\" for a quick overview:
.\" nroff -man -Tascii mapid.1 |less
.\"
.TH mapid 1 "August, 2007"
.SH NAME
mapid \- Monitoring Application Programming Interface deamon
.SH SYNOPSIS
.B mapid [-d] [-g] [-s] [-v] [-h]
.SH DESCRIPTION
.B mapid 
is a passive network monitoring deamon that captures packets from 
the network devices that have been configured and includes several
functionalities for returning results and packets to client applications
that use the Monitoring Application Programming Interface (
.B MAPI
). For 
.B MAPI
, please refer to the
.BR mapi (3)
page.
.SH OPTIONS
.B  -d, --daemon          
Run as a daemon
.br
.B  -g, --devgroup        
Bind only devices in <devgroup>
.br
.B  -s, --syslog          
Logging to syslog
.br
.B  -v, --version         
Display the version number
.br
.B  -h, --help            
Display help message
.SH BUGS
Please send bug reports to mapi@uninett.no
.SH "SEE ALSO"
.BR mapi (3),
.BR mapicommd (1),
.BR mapi_stdflib (3),
.BR mapi_dagflib (3),
.BR mapi_trackflib (3),
.BR mapi_anonflib (3),
.BR tcpdump (1),
.BR pcap (3)
